// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-8sZBqgyVqSBLTRvyukUOkUQegOkm5j8',
    appId: '1:460502729509:web:2cf0f0fd3dc7a9abbad0cc',
    messagingSenderId: '460502729509',
    projectId: 'login-51f81',
    authDomain: 'login-51f81.firebaseapp.com',
    storageBucket: 'login-51f81.firebasestorage.app',
    measurementId: 'G-4SZN914FJW',
);

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-8sZBqgyVqSBLTRvyukUOkUQegOkm5j8',
    appId: '1:460502729509:web:52f9da8043be64b5bad0cc',
    messagingSenderId: '460502729509',
    projectId: 'login-51f81',
    authDomain: 'login-51f81.firebaseapp.com',
    storageBucket: 'login-51f81.firebasestorage.app',
    measurementId: 'G-8644V2870G',
  );
}
